[toolchain]
channel = "1.61.0"
components = [
    "cargo",
    "clippy",
    "llvm-tools-preview",
    "rust-analysis",
    "rust-docs",
    "rust-src",
    "rust-std",
    "rustfmt",
]
targets = [
    "aarch64-apple-darwin",
    "aarch64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
]
