[package]
name = "malt"
version = "0.1.0"
authors = ["Bernardo Meurer <bernardo@meurer.org>"]
edition = "2018"

[dependencies]
discogs = { path = "../discogs" }
tokio = { version = "0.2.22", features = [ "rt-threaded", "tcp", "macros" ] }
